keys:
  - &users:
    - &olafkfreund age1twypjj94hwjeaf96kef0vfx9adg9uwucg4yjqe536fmexk3scsxq20yh6w
  - &hosts:
    - &aws_host age1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
    - &azure_host age1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
    - &local_vm age1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
    - age:
      - *olafkfreund
      - *aws_host
      - *azure_host
      - *local_vm